### ISSUE TITLE
Error when doing RNBoundary.add

### ISSUE THREAD

**Issue by CrypticGuy** [eddieowens/react-native-boundary#11]
I'm using the sample code provided in the Readme.md, and I'm getting this error in the log.
I think it has to do something with the configuration in the index.js, but I'm unsure how to correct it. Please help.

'error :(', { [TypeError: null is not an object (evaluating 'RNBoundary.add')] line: 192577, column: 19, sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }

**Comment by eddieowens** [comment]
Can I see how you import `RNBoundary`? And what are you passing into add?

**Comment by eddieowens** [comment]
I actually was just able to reproduce this by not running `react-native link react-native-boundary`. Can you check if you've linked the library?

**Comment by eddieowens** [comment]
Closing the issue as I strongly suspect this is just a misconfiguration. If I'm wrong, I'll reopen.

**Comment by CrypticGuy** [comment]
I linked it manually and it didn't work. Once I used react-native link react-native-boundary, it worked. Thankyou so much

**Comment by jacek213** [comment]
@eddieowens would be nice to document this one!

**Comment by TechSaq** [comment]
'react-native' is not recognized as an internal or external command, operable program or batch file.

Please help.
