### ISSUE TITLE
Boundary.add successfully added but event onEnter is not firing  

### ISSUE THREAD

**Issue by bhalaninimesh** [eddieowens/react-native-boundary#17]

**Comment by eddieowens** [comment]
Which OS? If it's Android, I'm currently working on a fix.

**Comment by bhalaninimesh** [comment]
@eddieowens 
Thanks for looking into this matter.
No it is not in android it is in ios i dont know what is an issue  if i mistaked installing or something else.
Please help me to find out the solution

**Comment by eddieowens** [comment]
Can you describe exactly what you're doing? Are you getting an error in the iOS logs? Are you getting logs on the JS side?

**Comment by bhalaninimesh** [comment]
I am getting a log from JS side but onEnter event is not triggering

**Comment by eddieowens** [comment]
@bhalaninimesh This is a limitation of iOS. The geofence library for iOS does not trigger an event for a monitored region if you are already in it (since technically you haven't _entered_ it or _exited_ it).
