### ISSUE TITLE
Integrate HeadlessJs into Android

### ISSUE THREAD

**Issue by eddieowens** [eddieowens/react-native-boundary#19]
Currently, Android events will not trigger in the background if the app is in doze mode. In order to get around this, @BrantApps suggested the following

>As far as I can tell, the `BoundaryEventBroadcastReceiver` is going to fire when we enter a geofence - all good there. With the code I wrote, these events would make it through to the JS layer if `RNBoundaryModule` has a context and a `resumed` owning activity. For an activity to be resumed, it needs to have been pretty close to being "on-screen" in the _recent_ past or _close_ future if that makes sense.
>
>In _native-native_ land (not RN), you would do your application work in the Job. I think the next evolution of this code for _react-native_ before it can be merged would be to;
>
> 1. In `BoundaryEventJobIntentService#sendEvent(String event, ArrayList<String> params)` refactor to start a HeadlessJS task with the name of the JS function to invoke with those parameters. Something like;
>
>```
>    private void sendEvent(String event, ArrayList<String> params) {
>        final Bundle bundle = new Bundle();
>        bundle.putString("event", event);
>        bundle.putStringArrayList("params", params);
>        new HeadlessJsTaskConfig(
>                "GeofenceDataChanged", // JS function to call
>                bundle, // The data to send
>                5000, // Timeout for the task
>                true); // Allowed in foreground
>    }
>```
>2. Figure out how to extend both `JobIntentService` and `HeadlessJsTaskService`, probably create a custom `JobIntentHeadlessJsTaskService` - has one of these been done already?
>3. Write the "GeofenceDataChanged" code in the JS layer to handle the events.
>4. Extend the library implementation to handle device restarts/location toggling. (Apparently on Android, the geofences are removed if the device reboots or the location functionality is toggled?)

I agree with this approach and think it's the best way to ensure all events trigger in the background.

**Comment by bhalaninimesh** [comment]
![Screen Shot 2019-04-02 at 5 23 27 PM](https://user-images.githubusercontent.com/47841328/55400915-c7e4cb80-556c-11e9-9cbe-b46edff9497f.png)

I am getting this error in android when adding geofence I think this is headlessJs issue tell me how to solve it?

**Comment by eddieowens** [comment]
@bhalaninimesh please open a separate issue. HeadlessJs has not been integrated.

**Comment by bhalaninimesh** [comment]
@eddieowens 
It is not HeadlessJS problem getting an error in BoundaryEventJobIntentService.java at line 59

**Comment by johnou** [comment]
@eddieowens some interesting notes here https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode

**Comment by eddieowens** [comment]
@johnou thanks! I'll check these out.

**Comment by eddieowens** [comment]
I have just integrated the `HeadlessJSTask` into android and simplified the flow for geofence events (see pr #27).

**Comment by jacek213** [comment]
@eddieowens documenting on how to use it for dead/background app would be really useful.
