### ISSUE TITLE
Event emmitting not functioning on Android

### ISSUE THREAD

**Issue by eddieowens** [eddieowens/react-native-boundary#3]
Read [this](https://stackoverflow.com/questions/51979251/react-native-events-fail-to-emit-when-called-from-intentservice) for context. I'm not sure as to why this is failing and if anyone has any suggestions or insights please comment here or on the SO thread. Thank you!

**Comment by cloudmobiledevelopment** [comment]
I've tested on Android 7.0, 8.1 and 9.0 and found that events are emitted on 7.0 but not on Android 8.1 and 9.0.  It appears that the problem is most likely with the Intent Service and doze mode in 8.0 as suggested in the stackoverflow [link](https://stackoverflow.com/questions/51979251/react-native-events-fail-to-emit-when-called-from-intentservice).  You might want to give Job Intent Service a try.

**Comment by cloudmobiledevelopment** [comment]
Here is some tips on geo fencing using Job Intent Service and BroadcastReceiver for geo fencing:

https://stackoverflow.com/questions/46675242/issue-moving-from-intentservice-to-jobintentservice-for-android-o

Maybe this might help.

**Comment by eddieowens** [comment]
@cloudmobiledevelopment thanks a lot for your research! I remember playing around with JobIntentService but I couldn't get consistent results. I'll revisit this though and follow up with what I've found.

**Comment by rfranczyk** [comment]
Hi Eddie, Wondering if by chance you were able to fix this issue by using JobIntentService? It would be a lifesaver.

**Comment by gtdrag** [comment]
+1

**Comment by eddieowens** [comment]
@rfranczyk working on it this week. I'll follow up with some results shortly.

**Comment by eddieowens** [comment]
So I've been playing around with the `JobIntentService` quite a bit and I can get it to work very nicely on the Android side. Geofences are triggered, and sent to the appropriate places but I can't get past the hurdle of the `ReactApplicationContext` being bound to the `RNBoundaryModule` class. 

As you can see [here in my branch](https://github.com/eddieowens/react-native-boundary/blob/feat/jobintentservice_refactor/android/src/main/java/com/eddieowens/services/BoundaryEventJobIntentService.java#L59), the context passed to `BoundaryEventJobIntentService` is not the `ReactApplicationContext` which I need to publish events. I'm a bit stumped as to how I can leverage this service and still have access to the context.

I'm definitely no Android expert so if anyone can chime in with some help I'd be very grateful!

**Comment by BrantApps** [comment]
Might you need the `JobIntentService#getApplicationContext()` @eddieowens ? I'm new to RN but proficient with Android. The `BaseContext` in this instance would refer to the underlying `android.app.Service`. So calling `getApplicationContext()` would invoke the `ContextWrapper` that should go off and find the application context... which I think is what we need?

**Comment by BrantApps** [comment]
Ok, I'm going to try another way (since it didn't seem to work with the above technique) with `LocalBroadcastManager`s - will let you know how it goes.

**Comment by eddieowens** [comment]
@BrantApps ya I've tried all of the contexts available but none of them can be cast to the `ReactApplicationContext` which doesn't make much sense to me. Thanks for looking into this too!

**Comment by eddieowens** [comment]
This has been fixed thanks to the work and help of @BrantApps. The `Boundary` will still not trigger in the background if the app has been dozed. Creating another issue to address that problem but this fix is in as of `1.0.7`
