### ISSUE TITLE
Way to test this library?

### ISSUE THREAD

**Issue by chrisspankroy** [eddieowens/react-native-boundary#37]
How do I test this library? In Xcode, I can simulate location events only when the app is currently running. It doesn't let me simulate the device's location after the app has been killed. Is there a way to see if this geofencing works after the app has been killed?

Same question for Android too.

**Comment by eddieowens** [comment]
I do manual testing or I use GPS mocking apps for Android. I'm not too sure how to test this in an automated way though.
