### ISSUE TITLE
not working on android

### ISSUE THREAD

**Issue by hasanal1995** [eddieowens/react-native-boundary#4]
events is not triggered, even if go out or go on boundary.

**Comment by eddieowens** [comment]
Ya this is already known. The JavaScript side is not receiving the events but they are being generated properly on the Android side. I spent quite a lot of time trying to figure out why but couldn't figure it out. If you have any ideas, I'd love to hear em.

See [this](https://github.com/eddieowens/react-native-boundary/issues/3) issue for tracking.
