### ISSUE TITLE
Can this run in the background?

### ISSUE THREAD

**Issue by reboss** [eddieowens/react-native-boundary#5]
Is there a way that I could create a background process that uses this code for geofencing, so something that runs while the app is not open?  If so, would if affect the users battery life significantly?

Thanks

**Comment by eddieowens** [comment]
This does run in the background and is very efficient in terms of battery usage. It makes use of the native geofencing libraries in both iOS and Android.

**Comment by kapilkarda** [comment]
How I can use that in the background, do you have any suggestion for that?
